language: php
php:
  - 7.0
  #- 5.6

git:
  depth: 5

before_install:
  - composer self-update
  - composer --version

install:
  - composer install
  - composer setup-satis

script:
  - composer cron
  - composer test

after_script:
  - ls -al; echo; ls -al web/
  - composer travis-satis

#End.
