language: php

php: 7.0
  #- 5.6

git:
  depth: 5

# before_install: composer validate --no-interaction
  # - composer self-update
  # - composer --version

install: composer install

before_script: composer setup-ci  # Was: composer setup-satis

script:
  - composer cron
  - composer test

after_script:
  - ls -alh; echo; ls -alh web/
  - composer travis-satis
  - composer validate --no-interaction

# End.
