language: php
php:
  - 5.6

git:
  depth: 3

before_install:
  - composer self-update
  - composer --version

install:
  - composer install
  - composer setup-satis
  - ls -al && ls -al web/

script:
  - composer cron
  - composer test

after_script:
  - grep -c IET-OU web/index.html

#End.
